name: example_CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lancer les tests    
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Installer sshpass
        run: sudo apt-get install -y sshpass

      # Ce code ne va pas fonctionner si l'host de la machine virtuelle est une adresse privée
      - name: Déployer via SSH
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            rm -rf log430-a25-labo0 || true
            git clone https://github.com/Vincent-Pisano/log430-a25-labo0.git
            cd log430-a25-labo0

            docker build -t labo0-calculator .
            
            docker stop labo0-calculator-container || true
            docker rm labo0-calculator-container || true

            docker run -d --name labo0-calculator-container labo0-calculator
          EOF